# This workflow is borrowed from reth: https://github.com/paradigmxyz/reth/blob/e04292247fff14ea93b4b0f6cf427bc9e4365c75/.github/workflows/dependencies.yml
# Automatically manages dependencies with periodic updates and checks for unused dependencies

name: Dependency Management

on:
  schedule:
    # Run weekly on Sunday
    - cron: "0 0 * * SUN"
  workflow_dispatch:
  # Allows for manual workflow execution

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: cargo-update
  TITLE: "chore(deps): weekly `cargo update`"
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

jobs:
  update_dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo update
        run: |
          cargo update --color never 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: Craft commit message and PR body
        id: craft_message
        run: |
          export cargo_update_log="$(cat cargo_update.log)"
          echo "commit_message<<EOF" >> $GITHUB_ENV
          printf "$TITLE\n\n$cargo_update_log\n" >> $GITHUB_ENV
          echo "EOF"
          echo "body<<EOF" >> $GITHUB_ENV
          echo "$BODY" | envsubst >> $GITHUB_ENV
          echo "EOF"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.craft_message.outputs.commit_message }}
          title: ${{ env.TITLE }}
          body: ${{ steps.craft_message.outputs.body }}
          branch: ${{ env.BRANCH }}

  check_unused_deps:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo udeps
        run: cargo +nightly udeps --output json

      - name: Analyze unused dependencies
        id: analyze_unused
        run: |
          export unused_deps="$(jq '.unused_deps' udeps_output.json)"
          echo "unused_deps<<EOF" >> $GITHUB_ENV
          echo "$unused_deps" >> $GITHUB_ENV
          echo "EOF"

      - name: Report Unused Dependencies
        run: |
          if [[ -z "${{ steps.analyze_unused.outputs.unused_deps }}" ]]; then
            echo "No unused dependencies found."
          else
            echo "Unused dependencies detected, see below:"
            echo "${{ steps.analyze_unused.outputs.unused_deps }}"
          fi

      

